### PR TITLE
Adds filter to VMMigrationDetails

### PR DESCRIPTION
**Pull request by gildub**
Resolves https://github.com/konveyor/virt-ui/issues/141

Allows to filter VM name, start and end times.
Status could be added if needed, meanwhile we better have useMockableQuery in place first to be aligned with final data.

### CODE REVIEW

**Comment by gildub** [comment]
@vconzola, please confirm this is as expected.

**Comment by vconzola** [comment]
@gildub In the filter dropdown, "Finished time" should be "End time" to be consistent with the column heading. Also, at some point we'll want to be able to filter (and sort) by status, but that can be handles as a separate PR, post beta.

**Comment by gildub** [comment]
@vconzola, could you please review?

I've also created https://github.com/konveyor/virt-ui/issues/146 to follow up with the status column.

**Review by vconzola — COMMENTED** [review]
LGTM. Thanks.

**Review by mturley — APPROVED** [review]
LGTM! One followup issue: the filters for start and end time should ideally be a date/time range picker instead of a search filter, but we don't quite have support for that in PF or FilterToolbar yet. There is a beta component https://www.patternfly.org/v4/components/date-picker we can use in the future, but it doesn't support times and ranges yet, and then once it does we'll also need to add a new type of FilterCategory for time ranges. Opened https://github.com/konveyor/virt-ui/issues/148.

**Pull request merged**
