### PR TITLE
Make most relevant status to surface

### PR DESCRIPTION
**Pull request by gildub**
Resolves https://github.com/konveyor/virt-ui/issues/64

### CODE REVIEW

**Comment by vconzola** [comment]
@gildub It looks like there are 5 possible status conditions that will be displayed, but I can't follow the code well enough to understand which icon will be shown for each condition. Can you elaborate in a comment? Thanks.

**Comment by gildub** [comment]
@vconzola, there are currently 3 available icons associated with Provider statuses: They are [`Ok, `Error` or `Warning`](https://github.com/konveyor/lib-ui/blob/master/src/components/StatusIcon/StatusIcon.tsx#L15).

We filter categories by severity as described [here](https://github.com/konveyor/virt-ui/issues/64#issuecomment-712928975). 

So when a given provider has at least one condition holding following category:
- `Critical` and `Error` then a Error icon will be displayed
- `Ready` then Ok icon to be used 
- Otherwise a warning icon to be displayed.

We could add more icons if needed along with a mapping between state and desired icon.

**Comment by vconzola** [comment]
@gildub Sounds good. Thanks for the explanation.

**Review by mturley — COMMENTED** [review]
@gildub LGTM! The only thing missing is that we should also use the new `mostSeriousCondition` helper for `getSortValues` on the OpenShiftProvidersTable, right?

**Comment by gildub** [comment]
@mturley, absolutely, I've added it to the `OpenShiftProvidersTable`

**Review by mturley — APPROVED** [review]
Nice!

**Pull request merged**
