### PR TITLE
Initial plan to display accordingly

### PR DESCRIPTION
**Pull request by gildub**
Takes care of a newly migration plans to display Spinner with a "Initializing" status before the backend catches up.

spin

### CODE REVIEW

**Comment by mturley** [comment]
I don't think Initializing is a warning condition, maybe we can display a spinner there? or an "info" (i) icon? @vconzola, thoughts?

**Comment by gildub** [comment]
@mturley, yeah info is surely more adapted then warning. I think we should augment lib-ui with an info Icon.

**Comment by mturley** [comment]
@vconzola Agreed! https://github.com/konveyor/lib-ui/issues/29

**Comment by vconzola** [comment]
@mturley @gildub If initializing is ongoing the spinner icon is more appropriate. Info is more for a static condition.

**Comment by mturley** [comment]
I agree that a spinner fits best here. This will only appear for a few seconds between clicking the Start button and when there is status information available.

**Comment by gildub** [comment]
@vconzola, @mturley, please check it out using a spinner (see description).

**Comment by vconzola** [comment]
@gildub I can't see it in the preview because when I try to create a plan it says that's not supported in mock mode. Can you drop a new screenshot/video in here?

**Comment by gildub** [comment]
@vconzola, as I mentioned in previous comment checkout the PR description.

**Comment by vconzola** [comment]
@gildub I don't understand. What PR description are you talking about? Is the screenshot/video above showing what it is after your PR or what it was before your PR. If after, then showing the spinner icon is not enough. It should also show status text, "Initializing".

**Comment by gildub** [comment]
@vconzola, sorry for the confusion, yet the video in the description of this PR shows what it looks like with the latest commits.
Ack we need the "Initializing" text. 
@mturley per your latest comment on https://github.com/konveyor/lib-ui/issues/29 the updated StatusIcon will take care of it too. So I'll push that one first and will come back to this one afterwards.

**Comment by gildub** [comment]
@vconzola, I've updated the video capture of the plan initialization in this PR description. Please review.

**Comment by vconzola** [comment]
Looks good. Thanks.

**Comment by gildub** [comment]
@mturley, this one is ready to be merged upon your last review. Ultimately we'll replace it once https://github.com/konveyor/lib-ui/pull/30 has been merged and a new release of lib-ui is available.

**Comment by mturley** [comment]
IMO let's just wait and merge https://github.com/konveyor/lib-ui/pull/30 first since it's pretty trivial, and this isn't super high priority. Would be nice to just get it done right.

**Comment by gildub** [comment]
@mturley, Now using lib-ui latest StatusIcon.

**Review by mturley — APPROVED** [review]
LGTM!

**Pull request merged**
