### PR TITLE
Add links to product documentation

### PR DESCRIPTION
**Pull request by gildub**
Resolves https://github.com/konveyor/virt-ui/issues/127

### CODE REVIEW

**Review by vconzola — CHANGES_REQUESTED** [review]
@gildub I get a #404 error when I click the link from the VM details expansion.

**Comment by mturley** [comment]
@vconzola I think that's expected until the docs go live. That's what Avital was saying in this comment: https://docs.google.com/presentation/d/1xUFNQPsQAmIrZdZNoG0G1D-UlOMc-OWFnKuwd_FR8Ao/edit?disco=AAAAKWfrTDc

> The splash page has not been published yet, so you will see a 404. However, this will be the permanent canonical URL for MTV.

We could hold off on merging this until the docs are released but we do know this will be the correct link.

**Review by mturley — APPROVED** [review]

**Comment by mturley** [comment]
I'm gonna go ahead and merge this to declutter open PRs, but if you disagree we can revert it.

**Comment by vconzola** [comment]
> @vconzola I think that's expected until the docs go live. That's what Avital was saying in this comment: https://docs.google.com/presentation/d/1xUFNQPsQAmIrZdZNoG0G1D-UlOMc-OWFnKuwd_FR8Ao/edit?disco=AAAAKWfrTDc
> 
> > The splash page has not been published yet, so you will see a 404. However, this will be the permanent canonical URL for MTV.
> 
> We could hold off on merging this until the docs are released but we do know this will be the correct link.

@mturley Gotcha. Makes sense. Although I'm not sure if we'll even have a direct doc link in the UI if the MA integration is going away.

**Comment by mturley** [comment]
That's true. Merged anyway so it'll be there when we re-enable that code.

**Pull request merged**
