### PR TITLE
Add Fingerprint field to VMware form in add provider modal

### LINKED ISSUE #159: Add "fingerprint" field when creating a VMware provider
Per @jortel, we'll need to ask the user for their certificate fingerprint when creating a VMware provider. This should use the PF FileUpload component.

### PR DESCRIPTION
**Pull request by mturley**
Resolves #159.

Screen Shot 2020-10-27 at 3 37 18 PM

### CODE REVIEW

**Comment by vconzola** [comment]
I'm sure "Fingerprint" is not sufficient as a field label, but don't know what is. :-) @jortel @fdupont-redhat What should this field be called?

**Comment by fdupont-redhat** [comment]
To be precise, it should be "Certificate SHA1 Fingerprint", but it's probably too long.

**Comment by vconzola** [comment]
Nope, not too long, and it's perfectly unambiguous. Thanks @fdupont-redhat .

**Comment by mturley** [comment]
Perfect. Thanks @fdupont-redhat @vconzola

**Comment by mturley** [comment]
Updated the field name, this is ready to go.

**Review by ibolton336 — APPROVED** [review]
LGTM!

**Pull request merged**
