### PR TITLE
VMMigrationDetails: Add select filter for Status column

### PR DESCRIPTION
**Pull request by gildub**
Resolves https://github.com/konveyor/virt-ui/issues/146

### CODE REVIEW

**Comment by vconzola** [comment]
@gildub Let's hold off on this until we have a chance to talk about it. I'm not sure we're talking about the same page where we want select filtering.

**Comment by mturley** [comment]
@vconzola was there another one? I seem to remember us talking about putting it on this page (#146)

**Comment by vconzola** [comment]
@mturley I thought we were talking about the Plans page where we have the status labels already in the table rows and the user could easily select Not started , Running / In-progress, Failed, or Completed from a dropdown. Ideally we'd have it on both pages and I think the same filter selection list would work in both places.

**Comment by mturley** [comment]
@vconzola I think maybe we talked about putting it in both places and forgot to open an issue for the plans page. Opened an issue: https://github.com/konveyor/virt-ui/issues/276

For this PR, if you go to the details of a plan (list of VMs) the Status filter there has a dropdown now. e.g. http://konveyor-virt-ui-pr-265-preview.surge.sh/plans/plantest-3

**Comment by vconzola** [comment]
@gildub @mturley One of the Status dropdown options is "OK"? What does this mean and when would a migration have status "OK"? I understand Completed, Not Started, On error, and In progress. But OK doesn't seem to fit into the lifecycle.

**Comment by mturley** [comment]
Good point, @gildub it looks like you're using "OK" as a catch-all when the status is unknown. I think we can just exclude it.

**Comment by gildub** [comment]
@vconzola, @mturley, good catch, "Ok" was a left over, absolutely not necessary. Thanks

**Review by mturley — APPROVED** [review]

**Pull request merged**
